### ISSUE TITLE
aria2c missing

### ISSUE THREAD

**Issue by smoretti** [hyoo/alphafold_singularity#6]
Hi

one of our users found that running 
```
cd /opt/alphafold/
scripts/download_all_data.sh
```
crashes because `Error: aria2c could not be found. Please install aria2c (sudo apt install aria2).`

I have installed it via "_alphafold.def_" in the container with `apt install -y aria2`
Is it required?

**Comment by hyoo** [comment]
This container doesn't intended to store all the database files since it is too big (more than 2TB). I would suggest to download and build database and pass the dataset path with `-B`. For building database, you can refer to https://github.com/kalininalab/alphafold_non_docker#download-all-databases if you don't like aria2c or go to the original repo (https://github.com/deepmind/alphafold#genetic-databases)

**Comment by smoretti** [comment]
OK, thanks for the information
